---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] | lower }}.yml"
    - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
    - "{{ ansible_facts['distribution'] | lower }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}.yml"
  tags:
    - always

- include: repo_pre_install.yml
  tags:
    - repo_server-install

- include: repo_install.yml
  tags:
    - repo_server-install

- include: repo_post_install.yml
  tags:
    - repo_server-config

- name: Create ssh keys for synchronising repo contents
  include_role:
    name: openstack.osa.ssh_keypairs
  args:
    apply:
      tags:
        - repo-key
        - repo_server-config
  vars:
      ssh_keypairs_setup_hosst: "{{ repo_ssh_keypairs_setup_host }}"
      ssh_keypairs_dir: "{{ repo_ssh_keypairs_dir }}"
      ssh_keypairs: "{{ repo_ssh_keypairs }}"
      ssh_keypairs_install_keys: "{{ repo_ssh_keypairs_install_keys }}"
      ssh_keypairs_install_ca: "{{ repo_ssh_keypairs_install_ca }}"
      ssh_keypairs_principals: "{{ repo_ssh_keypairs_principals }}"
  tags:
    - always

# TODO (jrosser) Remove this task for the Z release
- name: Remove legacy authorized keys file
  file:
    path: "{{ repo_service_home_folder }}/.ssh/authorized_keys"
    state: absent

- include: repo_sync_manager.yml
  when: inventory_hostname == groups['repo_all'][0]
  tags:
    - repo_server-config

- include: repo_install_constraints.yml
  when: inventory_hostname == groups['repo_all'][0]
  tags: repo_server-config

- name: Flush handlers
  meta: flush_handlers
