---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: reload nginx
  service:
    name: "nginx"
    enabled: yes
    state: restarted
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
  register: _restart
  until: _restart is success
  retries: 5
  delay: 2

- name: reload rsyncd
  service:
    name: "{{ rsyncd_service_name }}"
    enabled: yes
    state: restarted
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
  register: _restart
  until: _restart is success
  retries: 5
  delay: 2

- name: reload lsyncd
  service:
    name: "lsyncd"
    enabled: yes
    state: restarted
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
  register: _restart
  until: _restart is success
  retries: 5
  delay: 2

# TODO(odyssey4me):
# Remove these tasks in T. They are only present for the
# Q->R upgrade or for R->S upgrades for environments which
# were installed prior to R's release.
- name: Remove apt-cacher-ng package
  package:
    name: apt-cacher-ng
    state: absent
    purge: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
  listen:
    - cleanup apt-cacher-ng service

- name: Remove apt-cacher-ng data folders
  file:
    path: "{{ repo_service_home_folder }}/repo/{{ repo_pkg_cache_dirname | default('pkg-cache') }}"
    state: absent
  listen:
    - cleanup apt-cacher-ng service

- name: Remove apt-cacher-ng user
  user:
    name: "{{ repo_pkg_cache_owner | default('apt-cacher-ng') }}"
    state: absent
  listen:
    - cleanup apt-cacher-ng service

- name: Remove apt-cacher-ng group
  group:
    name: "{{ repo_pkg_cache_group | default('apt-cacher-ng') }}"
    state: absent
  listen:
    - cleanup apt-cacher-ng service

